In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import tree, ensemble
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.datasets import load_breast_cancer

(a) Use the breast cancer data set from Homework 0 to create a training set.
Recall that the label is 0 if the patient has breast cancer and 1 otherwise.
Compute the base rate of cancer occurrence over the entire data set.

In [45]:
cancer = load_breast_cancer()
q = np.where(cancer.target == 0)[0]
baseRate = len(q) / len(cancer.target)
print(baseRate)

0.37258347978910367
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


**On random seeds:** Many functions in scikit-learn, including models as well as utilities,
use randomization. For ease of grading, we will fix a random seed (we will use 101 throughout)
so as to make behavior deterministic. This can generally be done by passing in `random_state=101` to
the function; please consult documentation if unsure. Note to peer graders: this is purely for grading
convenience. Do not penalize harshly if the random seed has not been set properly.

(b) The goal is to build a decision tree that, based on the other features in the set,
predicts whether or not a patient has cancer.  So this is a classification problem.
Using tree.DecisionTreeClassifier and other functions in the scikit-learn library, one can
build a decision tree and calculate both its training accuracy when fitted to the entire data set
as well as its accuracy using 10-fold cross validation (which gives a better idea of true accuracy).

Vary the depth of your decision tree (use max_depth = $1, 2, \dots, 10$) and plot both training
accuracy and cross-validated accuracy (as a function of the depth, on the x-axis). Use 101 as your
random seed. Plot both curves on the same plot and use a legend to label them.

In [80]:
df = pd.DataFrame(cancer.data, columns = cancer.feature_names)
X = cancer.data
y = cancer.target

max_depth_range = [1,2,3,4,5,6,7,8,9,10]
train_accuracy = []
cvalid_accuracy = []

for i in max_depth_range:
    dtc = tree.DecisionTreeClassifier(max_depth=i, random_state=101)
    dtc = dtc.fit(X,y)
    train_accuracy.append(dtc.score(X, y))
    cvalid_accuracy.append(np.mean(cross_val_score(dtc, X, y, cv=10)))
print(train_accuracy)
print(cvalid_accuracy)
scatter = plt.scatter(df['mean compactness'], df['mean perimeter'], c=df['target'])
plt.xlabel('mean compactness')
plt.ylabel('mean perimeter')
plt.legend(handles=scatter.legend_elements()[0], labels=list(cancer.target_names))

[0.9226713532513181, 0.9420035149384886, 0.9789103690685413, 0.9824253075571178, 0.9947275922671354, 0.9982425307557118, 1.0, 1.0, 1.0, 1.0]
[0.8893170426065163, 0.9192042606516291, 0.9104010025062657, 0.913941102756892, 0.9139724310776941, 0.9174812030075186, 0.9139724310776941, 0.9156641604010025, 0.9156641604010025, 0.9156641604010025]


KeyError: 'target'

(c) Now try the random forest classifier of the scikit-learn library and use the best
depth you get from (b) as max_depth. Vary the number of trees in the forest via the parameter
n_estimators and plot its 10-fold cross-validated accuracy (use n_estimators = $1, 2, \dots, 20$).
Again, use 101 as your random seed. Do you see an improvement using random forests versus
using a single tree? (Note: use the n_estimators=1 result as the result for a single tree.)

(d) Using the method for building a decision tree you used in part (b), build a tree
but randomly hold out a $.2$,$.4$,$.6$, and $.8$ fraction of the data set (so you 
will need to build 4 different trees for each depth value). Use 101 as your random seed for both
the train-test split as well as the decision tree.
For each fraction held out, plot a curve of the test accuracy (the accuracy on the held-out
set) against depth. You should have four curves. Plot them all on the same plot and use
a legend to label them.